### ISSUE TITLE
Solr Search Not Working

### ISSUE THREAD

**Issue by jaredsmithse** [tambling/whetstone#2]
Entering a partial or even full query results in nothing being returned. No error code is thrown and nothing indicating that anything was found in the database. A guess would be that it is not setup to deal with the database correctly and is somehow just returning nothing.

**Comment by barcher** [comment]
From my understanding of it, Solr Search is only interacting with the Stone model, and shouldn't be interacting with the database at all.

**Comment by jaredsmithse** [comment]
We have taken out solr search in favor of completing a more lean mvp, issue gone for now.
