### ISSUE TITLE
Stone overview page still needs some help

### ISSUE THREAD

**Issue by tambling** [tambling/whetstone#6]
The sortable dragging events aren't binding, and the images are covering up recommended duration and difficulty text.

**Comment by tambling** [comment]
Sortable events bind, but the images remain a thorn in our already-thorny side. Thinking of just getting rid of them.

**Comment by tambling** [comment]
Don't imagine we'll be fixing this one lol

**Comment by hussain283** [comment]
Haha. Guess we won't.

How's everyone doing? It's been a while. :-)
